#!/usr/bin/env python3
"""Translate recovered straight-line TT295 float32 geometry into auditable TS.

Allocation/reference-count code is omitted; four uniform spline calls are
expressed through the independently validated Catmull–Rom implementation.
Every arithmetic instruction retains its original evaluation order.
"""
from pathlib import Path
import re,struct
ROOT=Path(__file__).resolve().parents[1]
ASM=ROOT/'research/makeup-geometry-tt295.asm'
lines=[]
for line in ASM.read_text().splitlines():
    m=re.match(r'\s*([\da-f]+):\s+(\S+)\s+(.*)',line)
    if m:lines.append((int(m[1],16),m[2],m[3].split(';')[0].strip()))

def block(start,end):
    constants={};out=[]
    for address,op,args in lines:
        if not start<=address<end:continue
        operands=[s.strip() for s in args.split(',')]
        dst=operands[0]
        if op in ['mov','movk']:
            assert dst.startswith('w') and operands[1].startswith('#')
            value=int(operands[1][1:],0)
            if op=='mov':constants[dst]=value
            else:constants[dst]=(constants[dst]&0xffff)|(value<<16)
        elif op=='ldr' and dst=='x8':continue
        elif op in ['ldr','str','ldp']:
            m=re.search(r'\[x8(?:, #(0x[\da-f]+))?\]',args)
            assert m,(hex(address),op,args)
            index=int(m[1] or '0',16)//8
            registers=operands[:2] if op=='ldp' else operands[:1]
            for offset,register in enumerate(registers):
                register='v'+register[1:] if register.startswith('d') else register
                if op=='str':out.append(f'  p[{index+offset}] = [...{register}];')
                else:out.append(f'  {register} = [...p[{index+offset}]];')
        elif op in ['fadd.2s','fsub.2s','fmul.2s','fdiv.2s']:
            symbol={'fadd.2s':'+','fsub.2s':'-','fmul.2s':'*','fdiv.2s':'/'}[op]
            a,b=operands[1:]
            out.append(f'  {dst} = [f({a}[0] {symbol} {b}[0]), f({a}[1] {symbol} {b}[1])];')
        elif op in ['dup.2s','fmov.2s','movi.2s']:
            if op=='dup.2s':value=struct.unpack('<f',struct.pack('<I',constants[operands[1]]))[0]
            elif op=='movi.2s':value=struct.unpack('<f',struct.pack('<I',int(operands[1][1:],0)<<int(operands[2].split('#')[1])))[0]
            else:value=float(operands[1][1:])
            out.append(f'  {dst} = [{value!r}, {value!r}];')
        elif op=='rev64.2s':out.append(f'  {dst} = [{operands[1]}[1], {operands[1]}[0]];')
        elif op=='mov.s':out.append(f'  {dst} = {operands[1]};')
        else:raise ValueError((hex(address),op,args))
    return '\n'.join(out)
header='''// Generated by tools/generate_makeup_tt295.py from recorded ARM64 instructions.
// Exact float32 operations; no fitted geometry coefficients.
import {makeupCatmullRom, type MakeupPoint} from './makeup-geometry';
type Pair = [number,number];
const f = Math.fround;
/** Original TT295 topology: base106 + dense44eye/26brow/64lip landmarks.
 * Coordinates must be native y-up, isotropic engine coordinates.
 * calcAlgorithmPointsV2 uses x/W and (1-y/H)*(H/W).
 */
export function buildTT295Positions(base:readonly MakeupPoint[],extra:readonly MakeupPoint[]):Float32Array {
  if(base.length!==106 || extra.length!==134) throw new Error('TT295 requires 106 base and 134 dense landmarks');
  const p:Pair[]=Array.from({length:295},()=>[0,0]);
  const copy=(source:readonly MakeupPoint[],from:number,to:number,count:number)=>{
    for(let i=0;i<count;i++)p[to+i]=[f(source[from+i].x),f(source[from+i].y)];
  };
  copy(base,0,0,33); copy(base,43,33,9); copy(base,80,42,4);
  copy(extra,0,46,44); copy(extra,44,90,26); copy(extra,70,116,64);
  const spline=(ids:number[],subdivisions:number[],dest:number,skip:number,count:number)=>{
    const out=makeupCatmullRom(ids.map(i=>({x:p[i][0],y:p[i][1]})),subdivisions,1);
    for(let i=0;i<count;i++)p[dest+i]=[out[i+skip].x,out[i+skip].y];
  };
'''
header+='  let '+', '.join(f'v{i}:Pair=[0,0]' for i in range(19))+', x9:Pair=[0,0];\n'
parts=[header,block(0x1c6eeb8,0x1c6f774),
 '  spline([1,235,239],[4,4],232,1,8);',
 block(0x1c6f9c4,0x1c6fc18),
 '  spline([31,255,259],[4,4],252,1,8);',
 block(0x1c6fe60,0x1c701e4),
 '  spline([279,280,282,284,285],[1,2,2,1],279,0,7);',
 block(0x1c70584,0x1c7063c),
 '  spline([286,287,289,291,292],[1,2,2,1],286,0,7);',
 '  return new Float32Array(p.flat());\n}\n']
(ROOT/'src/makeup-tt295.ts').write_text('\n'.join(parts))
print('Generated src/makeup-tt295.ts')
